name: Build-PhysX

on:
  workflow_dispatch:
    inputs:
      physxversion:
        description: "physx-sys version. (sample 0.11.1)"
        required: true

jobs:
  update-package:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./src/libmagicphysx
    steps:
      - uses: actions/checkout@v3
      - run: cargo test update_package_version -- ${{ inputs.physxversion }} --nocapture
      
      - name: Check update
        id: check_update
        run: git diff --exit-code || echo "changed=1" 
      
      - name: Commit files
        id: commit
        if: ${{ steps.check_update.outputs.changed == '1' }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "Update cargo.toml physx-sys version to ${{ inputs.physxversion }}" -a
      
      - name: Push changes
        if: ${{ steps.check_update.outputs.changed == '1' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  # Rust Platform target https://doc.rust-lang.org/nightly/rustc/platform-support.html

  win-x64:
    needs: [update-package]
    runs-on: windows-2019
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./src/libmagicphysx
    steps:
      - uses: actions/checkout@v3
      - run: rustup target add x86_64-pc-windows-msvc
      - run: cargo build --target x86_64-pc-windows-msvc --release
      - uses: actions/upload-artifact@v3
        with:
          name: win-x64
          path: ./src/libmagicphysx/target/x86_64-pc-windows-msvc/release/magicphysx.dll

  linux-x64:
    needs: [update-package]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./src/libmagicphysx
    steps:
      - uses: actions/checkout@v3
      - run: rustup target add x86_64-unknown-linux-gnu
      - run: cargo build --target x86_64-unknown-linux-gnu --release
      - uses: actions/upload-artifact@v3
        with:
          name: linux-x64
          path: ./src/libmagicphysx/target/x86_64-unknown-linux-gnu/release/libmagicphysx.so

  osx-x64:
    needs: [update-package]
    runs-on: macos-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./src/libmagicphysx
    steps:
      - uses: actions/checkout@v3
      - run: rustup target add x86_64-apple-darwin
      - run: cargo build --target x86_64-apple-darwin --release
      - uses: actions/upload-artifact@v3
        with:
          name: osx-x64
          path: ./src/libmagicphysx/target/x86_64-apple-darwin/release/libmagicphysx.dylib

  # download binary and git push

  git-push:
    needs: [win-x64, linux-x64, osx-x64]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: win-x64
          path: .src/MagicPhysX/runtimes/win-x64/native/libmagicphysx.dll
      - uses: actions/download-artifact@v3
        with:
          name: linux-x64
          path: .src/MagicPhysX/runtimes/linux-x64/native/libmagicphysx.so
      - uses: actions/download-artifact@v3
        with:
          name: osx-x64
          path: .src/MagicPhysX/runtimes/osx-x64/native/libmagicphysx.dylib
      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "Update physx lib runtime" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}