name: Build-PhysX

on:
  workflow_dispatch:
    inputs:
      physxversion:
        description: "physx-sys version. (sample 0.11.1)"
        required: true

jobs:
  update-package:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./src/libmagicphysx
    steps:
      - uses: actions/checkout@v3
      - run: cargo test update_package_version -- ${{ inputs.physxversion }} --nocapture
      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "Update cargo.toml physx-sys version to ${{ inputs.physxversion }}" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  # Rust Platform target https://doc.rust-lang.org/nightly/rustc/platform-support.html

  windows:
    needs: [update-package]
    runs-on: windows-2019
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./src/libmagicphysx
    steps:
      - uses: actions/checkout@v3
      - run: rustup target add x86_64-pc-windows-msvc
      - run: cargo build --target x86_64-pc-windows-msvc --release
      - run: cargo test move_target_lib -- x86_64-pc-windows-msvc win-x64 --nocapture
      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "Update windows physx lib runtime" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  # linux:
  #   needs: [update-package]
  #   strategy:
  #     matrix:
  #       target: ["x64", "arm64"]
  #   runs-on: ubuntu-latest
  #     timeout-minutes: 10
  #     defaults:
  #       run:
  #         working-directory: ./src/libmagicphysx
  #     steps:
  #       - uses: actions/checkout@v3
  #       - run: cargo test update_package_version -- ${{ inputs.physxversion }} --nocapture
  #       - run: cargo build --target  --release
  #       - run: cargo test move_target_lib -- win-x64 --nocapture
  #       - run: |
  #           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
  #           git config --local user.name "github-actions[bot]"
  #           git commit -m "Update cargo.toml physx-sys version to ${{ inputs.physxversion }}" -a    


  # macos:
